import styles from './Product.module.scss'
import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import { useState } from 'react'
import { TbPoint } from 'react-icons/tb'
import { IProduct } from '../../Interfaces/types-interfaces'

const Product = ({
  title,
  overview,
  demo,
  code,
  image,
  made,
  tech
}: IProduct) => {
  const [loading, setLoading] = useState(true)

  /* Display Made & Techs */
  const displayMade = made.map((m: string, i: number) => (
    <span key={i}>{i == made.length - 1 ? `${m}` : `${m} / `}</span>
  ))

  const displayTech = tech.map((t: string, i: number) => (
    <li key={i}>
      <TbPoint /> {t}
    </li>
  ))

  return (
    <div className={styles.container}>
      <Head>
        <title>{`Ismail Sevgi | ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.wrapper}>
        <div className={styles.content} />
        <Image
          layout="fill"
          objectFit="cover"
          src={image}
          alt={title}
          className={
            loading
              ? 'absolute z-1 object-center duration-700 ease-in-out grayscale blur-xl'
              : 'absolute z-1 object-center duration-700 ease-in-out grayscale-0 blur-0'
          }
          onLoadingComplete={() => setLoading(false)}
        />
        <div className={styles.info}>
          <h2>{title}</h2>
          <p>{displayMade}</p>
        </div>
        <Link href="/#projects" className={styles.backLink}>
          go back
        </Link>
      </div>
      <div className={styles.bottom}>
        <div className={styles.bottomInfo}>
          <h3>Project</h3>
          <h1>Overview</h1>
          <p>{overview}</p>
          <div className={styles.buttons}>
            <Link href={demo} target="_blank">
              Demo
            </Link>
            <Link href={code} target="_blank">
              Code
            </Link>
          </div>
        </div>
        <div className={styles.tech}>
          <p>technologies</p>
          <hr className="pb-2" />
          <ul>{displayTech}</ul>
        </div>
      </div>
    </div>
  )
}

export default Product
