import styles from './Welcome.module.scss'
import Image from 'next/image'
import Head from 'next/head'
import { useEffect, useState } from 'react'

const Welcome = () => {
  const [view, setView] = useState<boolean>(true)

  useEffect(() => {
    setTimeout(() => {
      setView(false)
    }, 1800)
  }, [])

  return (
    <div
      className={
        view
          ? 'w-full h-screen flex flex-col justify-center items-center gap-6 transition-all duration-500 ease-in-out bg-gradient-to-br from-violet-700 to-purple-800'
          : 'flex flex-col justify-center items-center gap-6 w-full h-screen transition-all duration-500 ease-in-out opacity-0 bg-gradient-to-br from-cyan-600 to-blue-600'
      }
    >
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.wrapper}>
        <div className={styles.spinner}></div>
      </div>
      <Image
        src="/assets/portfolio-image.png"
        alt="portfolio-image"
        width={400}
        height={400}
        className="rounded-full"
      />
      <h1 className={styles.text}>Wellcome</h1>
    </div>
  )
}

export default Welcome
