import styles from './Contact.module.scss'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { TForm } from '../../Interfaces/types-interfaces'

const Contact = () => {
  const [loading, setLoading] = useState<boolean>(true)
  const [formValue, setFormValue] = useState<TForm>({
    name: '',
    phone: '',
    email: '',
    comments: ''
  })

  const router = useRouter()

  const handleForm = (e: any) => {
    const { name, value } = e.target
    setFormValue({ ...formValue, [name]: value })
  }

  const resetForm = () => {
    router.push('/')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Ismail Sevgi | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.content}>
        <h3>Contact</h3>
        <h1>Get in touch</h1>
        <div className={styles.wrapper}>
          <div className={styles.leftWrapper}>
            <Image
              src="/assets/contact2.jpg"
              alt="image"
              layout="fill"
              className={
                loading
                  ? 'duration-700 ease-in-out grayscale blur-xl'
                  : 'duration-700 ease-in-out grayscale-0 blur-0'
              }
              onLoadingComplete={() => setLoading(false)}
            />
          </div>
          <div className={styles.rightWrapper}>
            <h2 className={styles.title}>Let&apos;s Talk</h2>
            <form
              onSubmit={resetForm}
              lang="en"
              action="https://getform.io/f/57933c42-58ce-46e3-906c-d1fef1047c60"
              method="POST"
              encType="multipart/form-data"
            >
              <main>
                <div className="flex flex-col">
                  <label>Name</label>
                  <input
                    type="text"
                    name="name"
                    value={formValue.name}
                    onChange={handleForm}
                    required
                  />
                </div>
                <div className="flex flex-col">
                  <label>Phone Number</label>
                  <input
                    type="text"
                    name="phone"
                    value={formValue.phone}
                    onChange={handleForm}
                    required
                  />
                </div>
              </main>
              <div className="flex flex-col py-2">
                <label>Email</label>
                <input
                  type="email"
                  name="email"
                  value={formValue.email}
                  onChange={handleForm}
                  required
                />
              </div>
              <div className="flex flex-col py-2">
                <label>Comments</label>
                <textarea
                  rows={10}
                  name="comments"
                  value={formValue.comments}
                  onChange={handleForm}
                  required
                ></textarea>
              </div>
              <button type="submit">Send</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Contact
