import Head from 'next/head'
import Main from '../components/Main/Main'
import About from '../components/About/About'
import Skills from '../components/Skills/Skills'
import Projects from '../components/Projects/Projects'
import { useRouter } from 'next/router'

export default function Home() {
  const route = useRouter()
  const routeTitle =
    route.asPath?.slice(2, 3).toUpperCase() + route.asPath?.slice(3)

  return (
    <div>
      <Head>
        <title>{`İsmail Sevgi | ${routeTitle ? routeTitle : 'Home'}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
    </div>
  )
}
